CREATE TABLE wms_inventory_item (
    inventory_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku VARCHAR2(40) NOT NULL UNIQUE,
    description VARCHAR2(200) NOT NULL,
    zone_code VARCHAR2(30) NOT NULL,
    on_hand_qty NUMBER(12) NOT NULL,
    allocated_qty NUMBER(12) NOT NULL,
    reorder_point NUMBER(12) NOT NULL,
    risk_code VARCHAR2(20) NOT NULL,
    updated_utc TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE wms_work_order (
    work_order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number VARCHAR2(40) NOT NULL UNIQUE,
    customer_name VARCHAR2(120) NOT NULL,
    area_code VARCHAR2(40) NOT NULL,
    status_code VARCHAR2(40) NOT NULL,
    due_utc TIMESTAMP NOT NULL,
    acceptance_criteria VARCHAR2(500)
);

CREATE TABLE wms_service_ticket (
    service_ticket_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_number VARCHAR2(40) NOT NULL UNIQUE,
    summary VARCHAR2(300) NOT NULL,
    system_area VARCHAR2(80) NOT NULL,
    priority_code VARCHAR2(20) NOT NULL,
    status_code VARCHAR2(40) NOT NULL,
    opened_utc TIMESTAMP NOT NULL,
    root_cause_hypothesis VARCHAR2(500),
    next_action VARCHAR2(500)
);
